### ISSUE TITLE
How can I print the Quaternion values (qx, qy, qz, qw) for each timestamp?

### ISSUE THREAD

**Issue by Jit-INP** [uoip/rgbd_ptam#1]
How can I print the **Quaternion values** (qx, qy, qz, qw) for each timestamp? Please help.

self.orientation = g2o.Quaternion()

**Comment by Jit-INP** [comment]
<img width="729" alt="Screen Shot 2020-06-01 at 11 13 58 AM" src="https://user-images.githubusercontent.com/59926833/83394780-726aaf80-a3f9-11ea-95dd-f57e4eb94193.png">

<img width="882" alt="Screen Shot 2020-06-01 at 11 19 16 AM" src="https://user-images.githubusercontent.com/59926833/83394928-c1184980-a3f9-11ea-895f-63962564c291.png">

When I am trying to print the Quaternion values (qx, qy, qz, qw), I am getting the object returned by the function in g2o library. How do I get the Quaternion values (qx, qy, qz, qw) for each timestamp? Please help.

**Comment by immaturehaan** [comment]
hello, do you know how to print the Quaternion values (qx, qy, qz, qw) of this issue?
